#
# (c) 2021 Center for Genome Platform Projects, Tohoku Medical Megabank Organization
#

FROM biocontainers/biocontainers:v1.0.0_cv4

USER root
RUN cd /usr/local/bin \
    && curl -L https://www.kingrelatedness.com/executables/Linux-king227.tar.gz | tar zxvf -

USER biodocker
